Feature/detail screen
nao-ni/teta pull request #1
Opened 2021-07-10 10:20 UTC by Omenawp

2021-07-12 11:29 UTC, NikolayUkhvarov requested changes

2021-07-12 11:29 UTC, NikolayUkhvarov commented on app/src/main/res/drawable-land/brg_poster.xml
> +        android:bottom="-10dp"
а почему отрицательные?

2021-07-12 11:29 UTC, NikolayUkhvarov commented on app/src/main/res/drawable/ic_profile.xml
> +    android:width="17dp"
странные нечетные размеры

2021-07-12 11:29 UTC, NikolayUkhvarov commented on app/src/main/res/drawable/ic_profile.xml
> +        android:fillColor="#020202"
цвета, размеры и отступы нужно вынести в ресурсы

2021-07-12 11:29 UTC, NikolayUkhvarov commented on app/src/main/res/layout-land/activity_movie_details.xml
> +                android:id="@+id/poster"
id для вьюх лучше указывать более читаемо (напрмиер, iv_poster или details_image_poster или image_poster)

2021-07-12 11:29 UTC, NikolayUkhvarov commented on app/src/main/res/values/strings.xml
> +    <string name="up18">18+</string>
у строк name тоже лучше делать более говорящий, можно с указанием места применения

2021-07-12 14:56 UTC, Omenawp commented on app/src/main/res/drawable-land/brg_poster.xml
> +        android:bottom="-10dp"
Если они не отрицательные, будет что-то вроде (скрин), а мне нужны только уголочки
![Screenshot 2021-07-12 144842](https://user-images.githubusercontent.com/66163836/125309389-665e5a80-e33a-11eb-86ec-d26c17fe62bc.jpg)

2021-07-14 08:24 UTC, NikolayUkhvarov requested changes

2021-07-14 08:24 UTC, NikolayUkhvarov commented on app/src/main/java/com/oelrun/teta/utils/RatingView.kt
> +        val filled = ContextCompat.getDrawable(context, R.drawable.ic_star_filled)!!
!! - плохо

2021-07-14 08:24 UTC, NikolayUkhvarov commented on app/src/main/res/values/dimens.xml
> +    <dimen name="movie_detail_padding_poster_double">-20dp</dimen>
для чего отрицательный паддинг?

2021-07-14 08:39 UTC, Omenawp commented on app/src/main/res/values/dimens.xml
> +    <dimen name="movie_detail_padding_poster_double">-20dp</dimen>
самый первый вопрос твой тут, я туда скрин приложила, мне нужны отрицательные паддинги, чтобы спрятать рамку и оставить уголочки

2021-07-14 08:41 UTC, Omenawp commented on app/src/main/java/com/oelrun/teta/utils/RatingView.kt
> +        val filled = ContextCompat.getDrawable(context, R.drawable.ic_star_filled)!!
override fun onDraw(canvas: Canvas) {
        **val filled = ContextCompat.getDrawable(context, R.drawable.ic_star_filled)
        val empty = ContextCompat.getDrawable(context, R.drawable.ic_star_blank)**

        for(i in 1..5) {
            val w = height * (i - 1)
            val pic = if(rating >= i) filled else empty
            **pic?.setBounds(w,0, w + height, height)
            pic?.draw(canvas)**
        }
    }
    
    Так будет лучше?

2021-07-14 09:21 UTC, Omenawp commented on app/src/main/res/values/dimens.xml
> +    <dimen name="movie_detail_padding_poster_double">-20dp</dimen>
Могу попробовать сделать тот же эффект через cardview, чтобы не использовать этот бекграунд с отрицательными паддингами

2021-07-14 10:02 UTC, Omenawp commented on app/src/main/res/values/dimens.xml
> +    <dimen name="movie_detail_padding_poster_double">-20dp</dimen>
Еще нашла, что из кода можно обрезать по background с закругленными краями

val iv = findViewById<ImageView>(R.id.image_poster)
iv.clipToOutline = true

как лучше сделать?

2021-07-14 10:36 UTC, NikolayUkhvarov commented on app/src/main/res/values/dimens.xml
> +    <dimen name="movie_detail_padding_poster_double">-20dp</dimen>
если этот вариант без отрицательного паддинга работает, то давай так лучше

2021-07-14 10:36 UTC, NikolayUkhvarov commented on app/src/main/java/com/oelrun/teta/utils/RatingView.kt
> +        val filled = ContextCompat.getDrawable(context, R.drawable.ic_star_filled)!!
ага

2021-07-16 08:00 UTC, NikolayUkhvarov approved these changes

2021-07-16 08:04 UTC, merged