add movies-fragment
nao-ni/teta pull request #3
Opened 2021-07-17 20:58 UTC by Omenawp

2021-07-20 07:51 UTC, NikolayUkhvarov requested changes

2021-07-20 07:51 UTC, NikolayUkhvarov commented on app/src/main/java/com/oelrun/teta/movies/GenresAdapter.kt
> +class GenresAdapter(private val clickListener: GenreListener)
nit отдельный класс можно было не делать

2021-07-20 07:51 UTC, NikolayUkhvarov commented on app/src/main/java/com/oelrun/teta/movies/GenresAdapter.kt
> +                if(selectedItems.contains(item.id)) {
в идеале, вьюхолдер не должен содержать логики, просто у genreDto есть поле selected: Boolean

2021-07-20 07:51 UTC, NikolayUkhvarov commented on app/src/main/java/com/oelrun/teta/movies/HeaderViewHolder.kt
> +        fun from(parent: ViewGroup): HeaderViewHolder {
это должно быть в адаптере

2021-07-20 07:51 UTC, NikolayUkhvarov commented on app/src/main/java/com/oelrun/teta/movies/MovieViewHolder.kt
> +        fun from(parent: ViewGroup): MovieViewHolder {
адаптер

2021-07-20 07:51 UTC, NikolayUkhvarov commented on app/src/main/java/com/oelrun/teta/movies/MoviesAdapter.kt
> +private const val ITEM_VIEW_TYPE_HEADER = 0
в компаньон

2021-07-20 07:51 UTC, NikolayUkhvarov commented on app/src/main/res/layout/fragment_movies.xml
> +        app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
в задании вроде был грид

2021-07-20 08:34 UTC, Omenawp commented on app/src/main/java/com/oelrun/teta/movies/HeaderViewHolder.kt
> +        fun from(parent: ViewGroup): HeaderViewHolder {
override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecyclerView.ViewHolder {
        return when(viewType) {
            ITEM_VIEW_TYPE_HEADER -> {
                val view = LayoutInflater.from(parent.context)
                    .inflate(R.layout.list_item_movie_header, parent, false)
                HeaderViewHolder(view)
            }
            ITEM_VIEW_TYPE_ITEM -> {
                val view = LayoutInflater.from(parent.context)
                    .inflate(R.layout.list_item_movie, parent, false)
                MovieViewHolder(view)
            }
            else -> throw ClassCastException("Unknown viewType $viewType")
        }
    }
    
    Т.е. я перенесла все из from в onCreateViewHolder, а из самих вьюхолдеров удаляю этот метод, правильно? Получается, что класс с хэдором у меня пустой например

2021-07-20 08:35 UTC, Omenawp commented on app/src/main/res/layout/fragment_movies.xml
> +        app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
грид для фильмов, а тут жанры, они в одну строчку идут

2021-07-20 08:43 UTC, Omenawp commented on app/src/main/java/com/oelrun/teta/movies/MoviesAdapter.kt
> +private const val ITEM_VIEW_TYPE_HEADER = 0
override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecyclerView.ViewHolder {
        return when(viewType) {
            ITEM_VIEW_TYPE_HEADER -> {
                val view = LayoutInflater.from(parent.context)
                    .inflate(R.layout.list_item_movie_header, parent, false)
                HeaderViewHolder(view)
            }
            ITEM_VIEW_TYPE_ITEM -> {
                val view = LayoutInflater.from(parent.context)
                    .inflate(R.layout.list_item_movie, parent, false)
                MovieViewHolder(view)
            }
            else -> throw ClassCastException("Unknown viewType $viewType")
        }
    }
Т.е. я перенесла все из from в onCreateViewHolder, а из самих вьюхолдеров удаляю этот метод, правильно? Получается, что класс с хэдором у меня пустой например

2021-07-20 08:44 UTC, Omenawp commented on app/src/main/java/com/oelrun/teta/movies/GenresAdapter.kt
> +                if(selectedItems.contains(item.id)) {
тоже думала,  перенесу

2021-07-20 08:45 UTC, Omenawp commented on app/src/main/java/com/oelrun/teta/movies/HeaderViewHolder.kt
> +        fun from(parent: ViewGroup): HeaderViewHolder {
```
override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecyclerView.ViewHolder {
        return when(viewType) {
            ITEM_VIEW_TYPE_HEADER -> {
                val view = LayoutInflater.from(parent.context)
                    .inflate(R.layout.list_item_movie_header, parent, false)
                HeaderViewHolder(view)
            }
            ITEM_VIEW_TYPE_ITEM -> {
                val view = LayoutInflater.from(parent.context)
                    .inflate(R.layout.list_item_movie, parent, false)
                MovieViewHolder(view)
            }
            else -> throw ClassCastException("Unknown viewType $viewType")
        }
    }
```
Т.е. я перенесла все из from в onCreateViewHolder, а из самих вьюхолдеров удаляю этот метод, правильно? Получается, что класс с хэдором у меня пустой например

2021-07-20 08:46 UTC, Omenawp commented on app/src/main/java/com/oelrun/teta/movies/GenresAdapter.kt
> +class GenresAdapter(private val clickListener: GenreListener)
не поняла, чего можно было не делать?

2021-07-20 08:51 UTC, Omenawp commented on app/src/main/java/com/oelrun/teta/movies/GenresAdapter.kt
> +                if(selectedItems.contains(item.id)) {
есть еще идея, чтобы не хранить эти значения в бд, можно в view.tag написать 0 или 1 в зависимости от selected или все же лучше с полем создавать, как ты предложил?

2021-07-20 19:17 UTC, NikolayUkhvarov commented on app/src/main/java/com/oelrun/teta/movies/GenresAdapter.kt
> +class GenresAdapter(private val clickListener: GenreListener)
сюда уже можно передать функцию

2021-07-20 19:17 UTC, NikolayUkhvarov commented on app/src/main/java/com/oelrun/teta/movies/GenresAdapter.kt
> +                if(selectedItems.contains(item.id)) {
с полем лучше

2021-07-20 19:19 UTC, NikolayUkhvarov commented on app/src/main/res/layout/fragment_movies.xml
> +        app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
не заметитл, да

2021-07-20 19:21 UTC, NikolayUkhvarov commented on app/src/main/java/com/oelrun/teta/movies/HeaderViewHolder.kt
> +        fun from(parent: ViewGroup): HeaderViewHolder {
вьюхолдер вроде можно было без тела создать

2021-07-22 10:40 UTC, NikolayUkhvarov approved these changes

2021-07-22 10:49 UTC, merged