add coroutines
nao-ni/teta pull request #5
Opened 2021-07-29 11:04 UTC by Omenawp

2021-08-03 08:05 UTC, NikolayUkhvarov requested changes

2021-08-03 08:05 UTC, NikolayUkhvarov commented on app/src/main/java/com/oelrun/teta/movies/MovieViewHolder.kt
> +    private fun setText(text: String, view: TextView) {
появилась какая-то лишняя логика
можешь сделать через утилс, расширение или делегат
но в вьюхолдере лучше просто сетить строку, даже без вызовов каких-то лишних функций

2021-08-04 15:32 UTC, NikolayUkhvarov requested changes

2021-08-04 15:32 UTC, NikolayUkhvarov commented on app/src/main/java/com/oelrun/teta/movies/MoviesFragment.kt
> +                if(!it) {
swipeContainer.isRefreshing = it не то же самое будет делать?

2021-08-04 15:32 UTC, NikolayUkhvarov commented on app/src/main/java/com/oelrun/teta/movies/MoviesFragment.kt
> +            moviesViewModel.errorMessage.collect {
nit:      moviesViewModel.errorMessage.collect { message ->
                message?.let {
  Toast.makeText(view.context, it, Toast.LENGTH_SHORT).show()
                    moviesViewModel.errorMessageShown()
}
           }

2021-08-04 15:32 UTC, NikolayUkhvarov commented on app/src/main/java/com/oelrun/teta/movies/MoviesViewModel.kt
> +                    Thread.sleep(2000)
стоит вынести в data source
у нас ведь там идет "загрузка из сети"

2021-08-04 15:32 UTC, NikolayUkhvarov commented on app/src/main/java/com/oelrun/teta/movies/MoviesViewModel.kt
> +                    Thread.sleep(2000)
и тут

2021-08-04 19:09 UTC, Omenawp commented on app/src/main/java/com/oelrun/teta/movies/MoviesFragment.kt
> +                if(!it) {
почти, я просто при первоначальной загрузке не хотела этот кружочек, думала что-то другое придумать. Но пока и правда лучше с ним)

2021-08-05 11:53 UTC, NikolayUkhvarov approved these changes

2021-08-05 12:07 UTC, merged